name: Update App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Uninstall App
        working-directory: /home/frappe/frappe-bench/apps
        run: |
          rm -rf tenant_management

      - name: Update
        working-directory: /home/frappe/frappe-bench
        run: |
          bench get-app https://github.com/Psami-wondah/tenant_management
          bench setup requirements --dev
          bench update --patch

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: Restart Bench
        working-directory: /home/frappe/frappe-bench
        run: |
          bench restart
