name: Update App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Pull
        working-directory: /home/frappe/frappe-bench/apps/tenant_management
        run: |
          git pull origin main

      - name: Update
        working-directory: /home/frappe/frappe-bench
        run: |
          bench update --patch

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: Restart Bench
        working-directory: /home/frappe/frappe-bench
        run: |
          bench restart
